[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "microsoft-kiota-serialization-multipart"
version = "1.7.1"
description = "Core abstractions for kiota generated libraries in Python"
authors = ["Microsoft <graphtooling+python@microsoft.com>"]
license = "MIT"
readme = "README.md"
keywords = ["kiota", "openAPI", "Microsoft", "Graph"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
]
homepage = "https://github.com/microsoft/kiota#readme"
repository = "https://github.com/microsoft/kiota-python"
documentation = "https://learn.microsoft.com/openapi/kiota/"
packages = [{include = "kiota_serialization_multipart"}]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
microsoft-kiota-abstractions = {path="../../abstractions/", develop=true}
pendulum = ">=3.0.0"

[tool.poetry.group.dev.dependencies]
yapf = "^0.40.2"
isort = "^5.13.2"
pylint = "^3.2.7"
mypy = "^1.11.2"
pytest = "^8.3.2"
pytest-asyncio = "^0.24.0"
poetry-plugin-mono-repo-deps = "^0.2.1"
microsoft-kiota-serialization-json = {path="../json/", develop=true}

[tool.mypy]
warn_unused_configs = true
files = "kiota_serialization_multipart"

[tool.yapf]
based_on_style = "pep8"
dedent_closing_brackets = true
each_dict_entry_on_separate_line = true
column_limit = 100

[tool.isort]
profile = "hug"

[tool.poetry-monorepo.deps]
enabled = true
commands = ["build", "export", "publish"]